# Generated by Django 4.2.6 on 2024-01-03 04:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_event_attendee_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
